{
  "formatVersion": "1.1",
  "component": {
    "group": "com.terence",
    "module": "statusmonitor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "statusmonitor-1.0.0.aar",
          "url": "statusmonitor-1.0.0.aar",
          "size": 28467,
          "sha512": "86f7daeb1b29f586abc7991915a41a38f9e6fbd28c12ec0c8dea1078fa0c58818e37652a6f2f2075cabbe11bda4fb2b4056f86813259f5ad6df13d0fafabf4c5",
          "sha256": "934d4ff96fee37b7944b1b68c151884b9e736df2dc24002e0e3065f4beeba51d",
          "sha1": "73880564172390f3a38fc23cdd50685c5414c951",
          "md5": "5538836e84b6b6f861add460a7c74a85"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "statusmonitor-1.0.0.aar",
          "url": "statusmonitor-1.0.0.aar",
          "size": 28467,
          "sha512": "86f7daeb1b29f586abc7991915a41a38f9e6fbd28c12ec0c8dea1078fa0c58818e37652a6f2f2075cabbe11bda4fb2b4056f86813259f5ad6df13d0fafabf4c5",
          "sha256": "934d4ff96fee37b7944b1b68c151884b9e736df2dc24002e0e3065f4beeba51d",
          "sha1": "73880564172390f3a38fc23cdd50685c5414c951",
          "md5": "5538836e84b6b6f861add460a7c74a85"
        }
      ]
    }
  ]
}
